site_name: "Piregal Hub"
theme:
  name: material
  language: es
  palette:
    - scheme: slate
      primary: black
      accent: blue grey
nav:
  - "ğŸ  Inicio | Home": index.md
  - "ğŸ›¡ï¸ Identidad | Identity":
      - "ğŸ‡ªğŸ‡¸ IntroducciÃ³n": v1-identidad/introduccion.md
      - "ğŸ‡¬ğŸ‡§ Introduction": v1-identidad/introduccion.en.md
  - "ğŸ› ï¸ Operativa | Ops":
      - "ğŸ‡ªğŸ‡¸ Reporte NCR": v4-operativa/ncr.md
      - "ğŸ‡¬ğŸ‡§ NCR Report": v4-operativa/ncr.en.md
