site_name: PIREGAL â€” EdiciÃ³n 2026
site_description: Cultura, Disciplina y Excelencia TÃ©cnica.
site_author: Sergio Piregal

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue grey
  font:
    text: Montserrat
    code: Roboto Mono
  icon:
    logo: material/shield-check-outline
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

nav:
  - 'ğŸ  Inicio': index.md
  - 'ğŸ“˜ Identidad':
      - 'QuiÃ©nes Somos': docs/v1-identidad/quienes-somos.md
  - 'ğŸ¤ Alianza Herculan':
      - 'PMEE 2026': docs/v3-alianza/pmee.md

plugins:
  - i18n:
      default_language: es
      languages:
        - es
        - en
  - search
