site_name: PIREGAL 2026
theme:
  name: material
  language: es

plugins:
  - i18n:
      default_language: es
      languages:
        - es
        - en
  - search

nav:
  - 'Inicio': index.md
  - 'Identidad': docs/v1-identidad/quienes-somos.md
  - 'Alianza': docs/v3-alianza/pmee.md
