site_name: "Piregal Hub"
theme:
  name: material
  language: es
  logo: assets/logo-piregal.png
  palette:
    - scheme: slate
      primary: black
      accent: blue grey
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top

plugins:
  - search
  - i18n:
      default_language: es
      languages:
        - locale: es
          name: EspaÃ±ol
          build: true
        - locale: en
          name: English
          build: true
      nav_translations:
        en:
          "ğŸ  Inicio": "ğŸ  Home"
          "ğŸ›¡ï¸ Identidad": "ğŸ›¡ï¸ Identity"
          "ğŸ¤ Alianza": "ğŸ¤ Alliance"
          "ğŸ› ï¸ Operativa": "ğŸ› ï¸ Operations"
          "ğŸ‘¨â€ğŸ”§ Equipo": "ğŸ‘¨â€ğŸ”§ Staff"

nav:
  - "ğŸ  Inicio": index.md
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
