site_name: PIREGAL 2026
site_description: Cultura, Disciplina y Excelencia TÃ©cnica.
site_author: Sergio Piregal

theme:
  name: material
  language: es
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue grey
  font:
    text: Montserrat
    code: Roboto Mono
  icon:
    logo: material/shield-check-outline
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - content.code.copy

nav:
  - 'ğŸ  Inicio': index.md
  - 'ğŸ“˜ Identidad':
      - 'QuiÃ©nes Somos': docs/v1-identidad/quienes-somos.md
  - 'ğŸ‘· Trabajador':
      - 'Manual de Conducta': docs/v2-trabajador/manual.md
  - 'ğŸ¤ Alianza Herculan':
      - 'PMEE 2026': docs/v3-alianza/pmee.md
  - 'ğŸ—ï¸ Operativa':
      - 'Protocolo de Obra': docs/v4-operativa/protocolo-obra.md
      - 'NCR e Incidencias': docs/v4-operativa/ncr.md
  - 'âš–ï¸ Compliance':
      - 'Transparencia': docs/v5-compliance/transparencia.md
