site_name: PIREGAL 2026
theme:
  name: material
  language: es
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight

nav:
  - 'ğŸ  Inicio': index.md
  - 'ğŸ“˜ Identidad': docs/v1-identidad/quienes-somos.md
  - 'ğŸ‘· Trabajador': docs/v2-trabajador/manual.md
  - 'ğŸ¤ Alianza Herculan': docs/v3-alianza/pmee.md
  - 'ğŸ—ï¸ Operativa':
      - 'Protocolo de Obra': docs/v4-operativa/protocolo-obra.md
      - 'NCR e Incidencias': docs/v4-operativa/ncr.md
  - 'âš–ï¸ Compliance': docs/v5-compliance/transparencia.md
