nav:
- 'ğŸ  Inicio': index.md
- 'ğŸ“˜ Identidad':
      - 'QuiÃ©nes Somos': docs/v1-identidad/quienes-somos.md
- 'ğŸ‘· Trabajador':
      - 'Manual de Conducta': docs/v2-trabajador/manual.md
- 'ğŸ¤ Alianza Herculan':
      - 'PMEE 2026': docs/v3-alianza/pmee.md
- 'ğŸ¤ operativa': 
      - 'protocolo-obra': docs/v4-operativa/protocolo-obra.md
- 'âš–ï¸ ncr:
      - 'ncr': docs/v4-operativa/ncr.md
- 'âš–ï¸ Compliance:
      - 'Transparencia': docs/v5-compliance/transparencia.md
